import os
import pandas as pd
from datetime import datetime, timedelta
import sqlite3
import logging
from .tuning_engine import TuningEngine

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class ReportingEngine:
    def __init__(self, db_path="trading_data_v2.db", report_dir="Reports/Paper"):
        self.db_path = db_path
        self.report_dir = report_dir
        os.makedirs(report_dir, exist_ok=True)

    def generate_daily_report(self, date_str=None):
        if date_str is None:
            date_str = datetime.now().strftime('%Y-%m-%d')
        
        logger.info(f"Generating report for {date_str}...")
        
        try:
            conn = sqlite3.connect(self.db_path)
            
            # 1. Fetch Trades for the day
            trades_df = pd.read_sql_query(f"""
                SELECT * FROM trades 
                WHERE date(entry_time) = '{date_str}' 
                OR date(exit_time) = '{date_str}'
            """, conn)
            
            # 2. Fetch Metrics for the day
            metrics_df = pd.read_sql_query(f"""
                SELECT * FROM strategy_metrics 
                WHERE date(timestamp) = '{date_str}'
            """, conn)
            
            if metrics_df.empty:
                logger.warning(f"No metrics found for {date_str}. Skipping report.")
                return None

            report_path = os.path.join(self.report_dir, f"{date_str}.md")
            
            with open(report_path, "w") as f:
                f.write(f"# Daily Paper Trading Performance: {date_str}\n\n")
                
                # --- PnL SUMMARY ---
                total_pnl = trades_df['pnl'].sum() if not trades_df.empty else 0
                win_rate = (len(trades_df[trades_df['pnl'] > 0]) / len(trades_df) * 100) if not trades_df.empty else 0
                
                f.write("## 💰 Financial Summary\n")
                f.write(f"- **Total Realized PnL**: ₹{total_pnl:.2f}\n")
                f.write(f"- **Win Rate**: {win_rate:.1f}%\n")
                f.write(f"- **Total Trades**: {len(trades_df)}\n\n")
                
                # --- STOCK PERFORMANCE ANALYZER ---
                f.write("## 🔍 Per-Stock Statistical Analysis\n")
                f.write("| Symbol | Max Z | Min Z | Hurst | Half-Life | In-Position % |\n")
                f.write("| :--- | :--- | :--- | :--- | :--- | :--- |\n")
                
                for symbol in metrics_df['symbol'].unique():
                    s_data = metrics_df[metrics_df['symbol'] == symbol]
                    max_z = s_data['z_score'].max()
                    min_z = s_data['z_score'].min()
                    avg_hurst = s_data['hurst'].mean()
                    avg_adx = s_data['adx'].mean()
                    regime = s_data['regime'].iloc[-1]
                    in_pos_time = (s_data['in_position'].mean() * 100)
                    
                    f.write(f"| {symbol} | {max_z:+.2f} | {min_z:+.2f} | {avg_hurst:.2f} | {avg_adx:.1f} | {regime} | {in_pos_time:.1f}% |\n")
                
                f.write("\n")
                
                # --- INTELLECTUAL TUNING ADVISOR ---
                f.write("## 🧠 Intellectual Tuning Advisor\n")
                f.write("Based on today's volatility and advanced metrics, here are the suggested optimizations:\n\n")
                
                for symbol in metrics_df['symbol'].unique():
                    s_data = metrics_df[metrics_df['symbol'] == symbol]
                    max_z = abs(s_data['z_score']).max()
                    avg_hurst = s_data['hurst'].mean()
                    threshold = s_data['threshold_used'].iloc[0]
                    
                    if avg_hurst > 0.55:
                        f.write(f"- **{symbol}**: ⚠️ **Trending Regime (H={avg_hurst:.2f})**. PCA spread is trending, not reverting. **Recommendation: DO NOT TRADE** or significantly increase threshold to {threshold + 1.0}.\n")
                    elif avg_hurst < 0.45:
                        f.write(f"- **{symbol}**: 💎 **High Conviction Reversion (H={avg_hurst:.2f})**. Strong mean-reversion signal. If not trading, consider **Lowering threshold to {max_z * 0.8:.1f}**.\n")
                    elif max_z < threshold * 0.7:
                        f.write(f"- **{symbol}**: ❄️ **Undershooting**. Today's movement was too small. Recommended threshold: **{max_z * 0.9:.1f}** to catch next breakout.\n")
                    else:
                        f.write(f"- **{symbol}**: ✅ **Aligned**. Current settings are compatible with today's noise levels.\n")
                
                f.write("\n\n---\n*Report generated by V3 Strategy Engine*")
            
            logger.info(f"Report saved to {report_path}")
            
            # --- TRIGGER AUTOMATED TUNING ---
            logger.info("Triggering mid-day automated tuning cycle...")
            tuner = TuningEngine(db_path=self.db_path)
            tuner.optimize_thresholds()
            
            return report_path
            
        except Exception as e:
            logger.error(f"Error generating report: {e}")
            return None
        finally:
            conn.close()

if __name__ == "__main__":
    engine = ReportingEngine()
    engine.generate_daily_report()
